# Generated by Django 3.2.4 on 2021-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='object_url',
            field=models.FileField(upload_to='urls/'),
        ),
    ]
